### ISSUE TITLE
Admin > Expected revalidating a resource after edit/add

### ISSUE THREAD

**Issue by coding-frank** [ordercloud-api/oc-accelerator#9]
I edited a buyer.

Issue:
The update  is visible in details page, but not in list view due to useOcResourceList staleTime: 300000 (caching)

Expected:
ResourceName: buyer is getting "revalidated", meaning cache cleared, and fresh data is visible in <ListView />.

Frank Arlt (Valtech)
frank.arlt@valtech.com

**Comment by erincdustin** [comment]
@coding-frank Hi Frank, the response from the `PUT v1/buyers/{buyerID}` call on the detail page should be getting used to update the cached data for the `GET v1/buyers/{buyerID}` query and any `GET v1/buyers` queries that contain the `buyerID` in the response as well (see [setQueryData](https://tanstack.com/query/latest/docs/reference/QueryClient#queryclientsetquerydata) in tanstack query docs)

I am not able to reproduce this behavior, so a little more information would be helpful.  Have you made updates to any of the arguments passed into the `useOcResourceList` hook? When you navigate back to the list view, are there any filters applied?

**Comment by coding-frank** [comment]
@erincdustin Hi. No, I didn't changed any arguments.
I edited a buyer and checked <ListView /> which fetches data with useOcResourceList:

<img width="575" alt="image" src="https://github.com/user-attachments/assets/628798f1-bb4b-49e4-aa57-06b278154c8b">
<img width="672" alt="Bildschirmfoto 2024-08-15 um 10 20 13" src="https://github.com/user-attachments/assets/994d097f-1559-4993-92ff-6584037f02db">
<img width="567" alt="Bildschirmfoto 2024-08-15 um 10 20 48" src="https://github.com/user-attachments/assets/72ab6b0a-666b-426a-99d7-6abdbc7935a5">
